name: Go CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22 
          
      - name: Verify go modules
        run: |
          go mod tidy
          go mod verify
          
      - name: Run tests
        run: go test ./...
